"""Centralized prompt configuration for SEANews."""
from __future__ import annotations

import json
import os
from typing import Any, Dict

_PROMPT_PATH = os.path.join(os.path.dirname(__file__), "prompts.json")


def _load_prompts() -> Dict[str, Any]:
    with open(_PROMPT_PATH, "r", encoding="utf-8") as handle:
        return json.load(handle)


_PROMPTS = _load_prompts()

TEAM_INSTRUCTIONS = _PROMPTS["TEAM_INSTRUCTIONS"]
EXPECTED_OUTPUT = _PROMPTS["EXPECTED_OUTPUT"]
RAG_AGENT_INSTRUCTIONS = _PROMPTS["RAG_AGENT_INSTRUCTIONS"]
FORMATTER_INSTRUCTIONS = _PROMPTS["FORMATTER_INSTRUCTIONS"]
SMALLTALK_INSTRUCTIONS_BASE = _PROMPTS["SMALLTALK_INSTRUCTIONS_BASE"]
ROUTER_INSTRUCTIONS_BASE = _PROMPTS["ROUTER_INSTRUCTIONS_BASE"]
RESEARCH_INSTRUCTIONS_BASE = _PROMPTS["RESEARCH_INSTRUCTIONS_BASE"]
RESEARCH_INSTRUCTIONS_SUFFIX = _PROMPTS["RESEARCH_INSTRUCTIONS_SUFFIX"]
VISION_INSTRUCTIONS = _PROMPTS["VISION_INSTRUCTIONS"]
OCR_PROMPT = _PROMPTS["OCR_PROMPT"]
SMALLTALK_PROMPT_WITH_USER = _PROMPTS["SMALLTALK_PROMPT_WITH_USER"]
SMALLTALK_PROMPT_DEFAULT = _PROMPTS["SMALLTALK_PROMPT_DEFAULT"]
ROUTER_PROMPT_TEMPLATE = _PROMPTS["ROUTER_PROMPT_TEMPLATE"]
TEAM_PROMPT_TEMPLATE = _PROMPTS["TEAM_PROMPT_TEMPLATE"]
FORMATTER_REPAIR_PROMPT_TEMPLATE = _PROMPTS["FORMATTER_REPAIR_PROMPT_TEMPLATE"]
TRANSLATE_TITLES_PROMPT_TEMPLATE = _PROMPTS["TRANSLATE_TITLES_PROMPT_TEMPLATE"]
TRACE_TEST_INSTRUCTIONS = _PROMPTS["TRACE_TEST_INSTRUCTIONS"]

# JS-only prompts (kept for shared config parity)
SYSTEM_PROMPT = _PROMPTS["SYSTEM_PROMPT"]
DOC_CONTEXT_PROMPT_TEMPLATE = _PROMPTS["DOC_CONTEXT_PROMPT_TEMPLATE"]
